# Generated by Django 5.2.8 on 2025-11-12 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=200)),
                ('editor_bio', models.TextField()),
                ('editor_photo', models.ImageField(blank=True, null=True, upload_to='editor_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('publisher', 'Publisher'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('reader', 'Reader')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_by_editor', to='news2u.customuser')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_by_journalist', to='news2u.customuser')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_by_publisher', to='news2u.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AdminApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('publisher', 'Publisher'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('reader', 'Reader')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('declined_for', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news2u.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalist_name', models.CharField(max_length=200)),
                ('journalist_bio', models.TextField()),
                ('journalist_photo', models.ImageField(blank=True, null=True, upload_to='journalist_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(blank=True, related_name='journalists', to='news2u.editor')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_description', models.TextField()),
                ('journalists', models.ManyToManyField(blank=True, related_name='publishers', to='news2u.journalist')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_title', models.CharField(max_length=255)),
                ('newsletter_content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Articles included in this newsletter', related_name='newsletters', to='news2u.article')),
                ('editor', models.ForeignKey(blank=True, help_text='Newsletter edited by ...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_newsletters', to='news2u.editor')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='news2u.journalist')),
                ('publisher', models.ForeignKey(blank=True, help_text='Publisher if newsletter is from a publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='news2u.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='editor',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='editors', to='news2u.publisher'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_journalists', models.ManyToManyField(blank=True, related_name='subscribers', to='news2u.journalist')),
                ('subscribed_publishers', models.ManyToManyField(blank=True, related_name='subscribers', to='news2u.publisher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news2u.customuser')),
            ],
        ),
    ]
