# Generated by Django 5.2.8 on 2025-11-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Reader',
        ),
    ]
