# Generated by Django 5.2.8 on 2025-11-14 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0002_rename_subscription_reader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='subscribed_journalists',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='subscribed_publishers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to='news2u.journalist'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to='news2u.publisher'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_logo',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_logo/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_by_editor', to='news2u.editor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_by_journalist', to='news2u.journalist'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_by_publisher', to='news2u.publisher'),
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expiry_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
