# Generated by Django 5.2.8 on 2025-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0004_editor_user_journalist_user_publisher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='declined_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
