# Generated by Django 5.2.8 on 2025-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0005_customuser_declined_for_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapproval',
            name='declined_for',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete Information'), ('duplicate', 'Duplicate Account'), ('spam', 'Suspected Spam/Fraud'), ('other', 'Other (see notes)')], max_length=50, null=True),
        ),
    ]
