# Generated by Django 5.2.8 on 2025-11-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0006_alter_adminapproval_declined_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Articles included in this newsletter', related_name='articles_in_newsletters', to='news2u.article'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalist_newsletters', to='news2u.journalist'),
        ),
    ]
