# Generated by Django 5.2.8 on 2025-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0008_alter_reader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reader_photos/'),
        ),
    ]
