# Generated by Django 5.2.8 on 2025-11-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0009_reader_reader_interests_reader_reader_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(blank=True, null=True, upload_to='article_photos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_comments',
            field=models.TextField(blank=True, help_text='Editor feedback', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Assignment'), ('in_review', 'Being Edited'), ('ready_to_publish', 'Ready to Publish'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_by_editor', to='news2u.editor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_by_publisher', to='news2u.publisher'),
        ),
    ]
