# Generated by Django 5.2.8 on 2025-11-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0010_article_article_photo_article_editor_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('ready_to_publish', 'Ready to Publish'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('ready_to_publish', 'Ready to Publish'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher')], default='draft', max_length=30),
        ),
    ]
