# Generated by Django 5.2.8 on 2025-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0013_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('ready_to_publish', 'Approved for Publication'), ('in_review_publisher', 'Under Publisher Review'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher'), ('decline_article', 'Declined')], default='draft', max_length=30),
        ),
    ]
