# Generated by Django 5.2.8 on 2025-11-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0014_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalist_newsletters', to='news2u.journalist'),
        ),
    ]
