# Generated by Django 5.2.8 on 2025-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0015_alter_newsletter_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
