# Generated by Django 5.2.8 on 2025-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0016_newsletter_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('in_review_publisher', 'Under Publisher Review'), ('ready_to_publish', 'Approved for Publication'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher')], default='draft', max_length=30),
        ),
    ]
