# Generated by Django 5.2.8 on 2025-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0017_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('in_review_publisher', 'Under Publisher Review'), ('ready_to_publish', 'Approved for Publication'), ('published_newsletter', 'Published by Journalist'), ('published_newsletter_by_publisher', 'Published by Publisher')], default='draft', max_length=50),
        ),
    ]
