# Generated by Django 5.2.8 on 2025-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0018_alter_newsletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='editor_interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
