# Generated by Django 5.2.8 on 2025-11-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2u', '0021_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='email',
        ),
    ]
